# Imports & setup

In [1]:
# Move up to parent folder
%cd ..

c:\Users\David Harler Jr\OneDrive\Desktop\dataClass\06-cod-analysis\03 CDL PrizePicks Betting\cdl_prizepicks_betting_apps\v04

In [2]:
# Import selenium
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

In [3]:
# Import undetected chromedriver
import undetected_chromedriver as uc

In [4]:
# Import time & pandas
import time
import pandas as pd

In [5]:
# Set Chrome Options, specifically to allow location tracking on PrizePicks
capabilities = DesiredCapabilities().CHROME

chrome_options = uc.ChromeOptions()
chrome_options.add_argument("--incognito")
chrome_options.add_argument("--disable-infobars")
chrome_options.add_argument("start-maximized")
chrome_options.add_argument("--disable-extensions")
chrome_options.add_argument("--disable-popup-blocking")

prefs = {
    'profile.default_content_setting_values':
    {
        'notifications': 1,
        'geolocation': 1
    },

    'profile.managed_default_content_settings':
    {
        'geolocation': 1
    },
}

chrome_options.add_experimental_option('prefs', prefs)
capabilities.update(chrome_options.to_capabilities())

In [6]:
# Open browser
driver = uc.Chrome(options = chrome_options)

In [9]:
# Visit PrizePicks Website
driver.get("https://app.prizepicks.com/")
time.sleep(5)

In [11]:
# Close initial pop-up
WebDriverWait(driver, 20).until(EC.presence_of_all_elements_located((By.CLASS_NAME, "close")))
time.sleep(5)
driver.find_element(By.XPATH, "/html/body/div[3]/div[3]/div/div/button").click()
time.sleep(5)

In [12]:
# Find all league buttons
league_buttons = driver.find_element(By.ID, "scrollable-area").text.split('\n')
league_buttons

['MMA',
 'WNBA',
 'NBA',
 'CS2',
 'MLB',
 'NHL',
 'SOCCER',
 'WNBA1H',
 'MLBLIVE',
 'PGA',
 'BOXING',
 'LoL',
 'COD',
 'NHL1P',
 'TENNIS',
 'NBA1H',
 'NFLSZN',
 'LAX',
 'DARTS',
 'CWS',
 'APEX',
 'TRUCKS',
 'UFL',
 'SOCCERSZN',
 'NASCAR',
 'XFINITY']

In [13]:
# Get index of COD in league_buttons list
cod_index = league_buttons.index("COD") + 1
cod_index

13

In [14]:
# Navigate to COD tab using COD index, clicking right arrow if necessary
if cod_index <= 12:
    driver.find_element(By.XPATH, "//*[@id='scrollable-area']/button[" + str(cod_index) + "]").click()
elif cod_index <= 15:
    driver.find_element(By.XPATH, "//*[@id='board']/nav[1]/button[2]").click()
    time.sleep(5)
    driver.find_element(By.XPATH, "//*[@id='scrollable-area']/button[" + str(cod_index) + "]").click()
elif cod_index <= 18:
    driver.find_element(By.XPATH, "//*[@id='board']/nav[1]/button[2]").click()
    time.sleep(5)
    driver.find_element(By.XPATH, "//*[@id='board']/nav[1]/button[2]").click()
    time.sleep(5)
    driver.find_element(By.XPATH, "//*[@id='scrollable-area']/button[" + str(cod_index) + "]").click()
time.sleep(5)

In [10]:
# Initilize an empty list to hold the player props
player_props = []

In [11]:
# Get the stat container and various stats 
stat_container = WebDriverWait(driver, 1).until(EC.visibility_of_element_located((By.CLASS_NAME, "stat-container")))
categories = driver.find_element(By.CSS_SELECTOR, ".stat-container").text.split('\n')

In [12]:
# Remove Maps 1 - 3 Kills (Combo)
if "MAPS 1-3 Kills (Combo)" in categories:
    categories.remove("MAPS 1-3 Kills (Combo)")
categories

['MAPS 1-3 Kills', 'MAP 1 Kills', 'MAP 2 Kills', 'MAP 3 Kills']

In [13]:
# Get player projections

# Print the beginning of the logging.
print("-----------------------------")

print("Beginning Data Retrieval     ")
print("-----------------------------")
print("")

# Loop through categories
for category in categories:
    driver.find_element(By.XPATH, f"//div[text()='{category}']").click()
    time.sleep(5)

    # Test print statement
    print(f"{category}")
    
    # Get list of all projections for current category
    projectionsPP = driver.find_elements(By.ID, "test-projection-li")

    # Loop through current list of projections
    for i in range(len(projectionsPP)):

        # Get line info for each player prop
        player = projectionsPP[i].find_element(By.ID, "test-player-name").text
        team_abbr = projectionsPP[i].find_element(By.ID, "test-team-position").text.split(" - ")[0]
        player_line = float(driver.find_element(
            By.XPATH, 
            '/html/body/div[1]/div/div[3]/div[1]/div/main/div/div/div[1]/div[3]/ul/li[' + str(i + 1) + ']/div[3]/div/div/div/div[1]'
        ).text)

        # Append prop to our list
        player_props.append({
            "player": player, 
            "team_abbr": team_abbr, 
            "prop": category.split(" ")[1] if category != "MAPS 1-3 Kills" else "0", 
            "line": player_line
        })

        # Test print statement
        print(f"{player} {team_abbr} | {player_line}")

    # Print Formatting
    print("")
    
# Indicate that Data Loading is complete.
print("-----------------------------")
print("Data Retrieval Complete      ")
print("-----------------------------")

-----------------------------
Beginning Data Retrieval
-----------------------------

MAPS 1-3 Kills
Abuzah SEA | 51.0
Huke SEA | 50.0
Breszy SEA | 46.5
04 SEA | 54.0
CleanX TOR | 56.0
Envoy TOR | 49.0
Insight TOR | 46.5
Scrap TOR | 57.5
Accuracy MIN | 48.5
Lynz MIN | 53.0
Standy MIN | 51.5
Gunless MIN | 48.0
Priestahh BOS | 48.0
Snoopy BOS | 54.0
Beans BOS | 52.0
MajorManiak BOS | 47.0
Clayster CAR | 48.0
Gwinn CAR | 53.0
FeLo CAR | 47.0
TJHaLy CAR | 48.0
Diamondcon LAG | 49.0
Estreal LAG | 50.0
Fame LAG | 48.0
Flames LAG | 49.0

MAP 1 Kills
Abuzah SEA | 24.5
Huke SEA | 22.5
Breszy SEA | 21.5
04 SEA | 23.5
CleanX TOR | 25.0
Envoy TOR | 22.5
Insight TOR | 20.5
Scrap TOR | 25.5
Accuracy MIN | 21.5
Lynz MIN | 23.5
Standy MIN | 23.0
Gunless MIN | 22.0
Priestahh BOS | 21.5
Snoopy BOS | 24.5
Beans BOS | 23.5
MajorManiak BOS | 20.5
Clayster CAR | 22.0
Gwinn CAR | 24.0
FeLo CAR | 21.5
TJHaLy CAR | 21.5
Diamondcon LAG | 22.5
Estreal LAG | 23.5
Fame LAG | 21.5
Flames LAG | 22.5

MAP 2 Kills
Abuzah SEA | 6.5
Huke SEA | 6.5
Breszy SEA | 6.0
04 SEA | 7.5
CleanX TOR | 7.0
Envoy TOR | 6.0
Insight TOR | 6.0
Scrap TOR | 7.0
Accuracy MIN | 6.0
Lynz MIN | 7.5
Standy MIN | 7.0
Gunless MIN | 6.0
Priestahh BOS | 6.0
Snoopy BOS | 7.5
Beans BOS | 6.5
MajorManiak BOS | 6.5
Clayster CAR | 6.0
Gwinn CAR | 6.5
FeLo CAR | 5.5
TJHaLy CAR | 7.0
Diamondcon LAG | 6.5
Estreal LAG | 6.5
Fame LAG | 6.0
Flames LAG | 6.5

MAP 3 Kills
Abuzah SEA | 20.5
Huke SEA | 21.5
Breszy SEA | 19.5
04 SEA | 23.5
CleanX TOR | 23.5
Envoy TOR | 21.0
Insight TOR | 20.5
Scrap TOR | 25.5
Accuracy MIN | 21.5
Lynz MIN | 22.5
Standy MIN | 22.0
Gunless MIN | 20.5
Priestahh BOS | 21.0
Snoopy BOS | 22.5
Beans BOS | 22.5
MajorManiak BOS | 20.5
Clayster CAR | 20.5
Gwinn CAR | 23.0
FeLo CAR | 20.5
TJHaLy CAR | 21.0
Diamondcon LAG | 20.5
Estreal LAG | 20.5
Fame LAG | 21.0
Flames LAG | 21.5

-----------------------------
Data Retrieval Complete
-----------------------------

In [14]:
# Convert our list of player props to a dataframe
player_props_df = pd.DataFrame(player_props)
player_props_df

        player team_abbr prop  line
0       Abuzah       SEA    0  51.0
1         Huke       SEA    0  50.0
2       Breszy       SEA    0  46.5
3           04       SEA    0  54.0
4       CleanX       TOR    0  56.0
..         ...       ...  ...   ...
91      TJHaLy       CAR    3  21.0
92  Diamondcon       LAG    3  20.5
93     Estreal       LAG    3  20.5
94        Fame       LAG    3  21.0
95      Flames       LAG    3  21.5

[96 rows x 4 columns]

In [45]:
# Set proptype column to int
player_props_df['prop'] = player_props_df['prop'].astype(int)

# Set player and team_abbr columns to str
player_props_df['player'] = player_props_df['player'].astype(str)
player_props_df['team_abbr'] = player_props_df['team_abbr'].astype(str)

# Drop duplicates before sorting
player_props_df.drop_duplicates(subset = ['player', 'prop'], inplace = True)

# Add player_lower column for sorting
player_props_df["player_lower"] = player_props_df['player'].str.lower()

# Sort player_props_df by prop, team, and player_lower
player_props_df = player_props_df.sort_values(by = ["prop", "team_abbr", "player_lower"])

# Drop the player_lower column
player_props_df = player_props_df.drop("player_lower", axis = 1)

# Reset index & return
player_props_df = player_props_df.reset_index(drop=True)

player_props_df

        player team_abbr  prop  line
0        Beans       BOS     0  53.5
1    Pentagrxm       BOS     0  49.5
2    Priestahh       BOS     0  49.5
3       Snoopy       BOS     0  56.5
4     Clayster       CAR     0  47.5
..         ...       ...   ...   ...
123     Standy       MIN     3  22.5
124         04       SEA     3  24.0
125     Abuzah       SEA     3  20.5
126     Breszy       SEA     3  21.5
127       Huke       SEA     3  22.5

[128 rows x 4 columns]

In [57]:
pd.reset_option('display.max_rows')
# pd.set_option('display.max_rows', None)

In [5]:
from utils.webscraper import *

In [6]:
from utils.setup.setup import *

In [6]:
# 1. Get current player props from PrizePicks
player_props_df = scrape_prizepicks()
player_props_df

MAP 1 Kills
MAP 2 Kills
MAP 3 Kills

      player team_abbr  prop  line
0   Clayster       CAR     1  23.5
1       FeLo       CAR     1  22.5
2      Gwinn       CAR     1  25.5
3     TJHaLy       CAR     1  24.5
4      Lucky       MIA     1  21.5
..       ...       ...   ...   ...
67      Huke       SEA     3  22.5
68    CleanX       TOR     3  22.5
69     Envoy       TOR     3  22.5
70   Insight       TOR     3  20.5
71     Scrap       TOR     3  24.0

[72 rows x 4 columns]

In [49]:
# 2. Load cdlDF
cdlDF = load_and_clean_cdl_data()
cdlDF

c:\Users\David Harler Jr\OneDrive\Desktop\dataClass\06-cod-analysis\03 CDL PrizePicks Betting\cdl_prizepicks_betting\cdl-betting-app-v03\setup\setup.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cdlDF = sqlio.read_sql_query("SELECT * FROM cdl_data", conn)

,match_id,match_date,match_day,player,team,map_num,map_name,gamemode,kills,deaths,...,series_result,map_wl,team_abbr,team_icon,opp,opp_abbr,opp_score,total_score,score_diff,dummy_x
0,27193,2023-12-08,Friday,aBeZy,Atlanta FaZe,1,Karachi,Hardpoint,24,24,...,1,W,ATL,FaZe,Boston Breach,BOS,238,488,12,0
1,27193,2023-12-08,Friday,Cellium,Atlanta FaZe,1,Karachi,Hardpoint,21,19,...,1,W,ATL,FaZe,Boston Breach,BOS,238,488,12,0
2,27193,2023-12-08,Friday,Drazah,Atlanta FaZe,1,Karachi,Hardpoint,25,22,...,1,W,ATL,FaZe,Boston Breach,BOS,238,488,12,0
3,27193,2023-12-08,Friday,Simp,Atlanta FaZe,1,Karachi,Hardpoint,33,23,...,1,W,ATL,FaZe,Boston Breach,BOS,238,488,12,0
4,27193,2023-12-08,Friday,Capsidal,Boston Breach,1,Karachi,Hardpoint,24,26,...,0,L,BOS,Breach,Atlanta FaZe,ATL,250,488,-12,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5203,70647,2024-05-16,Thursday,TJHaLy,Carolina Royal Ravens,4,Rio,Hardpoint,21,25,...,0,L,CAR,Ravens,OpTic Texas,TX,250,430,-70,0
5204,70647,2024-05-16,Thursday,Dashy,OpTic Texas,4,Rio,Hardpoint,19,22,...,1,W,TX,OpTic,Carolina Royal Ravens,CAR,180,430,70,0
5205,70647,2024-05-16,Thursday,Kenny,OpTic Texas,4,Rio,Hardpoint,17,25,...,1,W,TX,OpTic,Carolina Royal Ravens,CAR,180,430,70,0
5206,70647,2024-05-16,Thursday,Pred,OpTic Texas,4,Rio,Hardpoint,27,23,...,1,W,TX,OpTic,Carolina Royal Ravens,CAR,180,430,70,0
5207,70647,2024-05-16,Thursday,Shotzzy,OpTic Texas,4,Rio,Hardpoint,32,22,...,1,W,TX,OpTic,Carolina Royal Ravens,CAR,180,430,70,0

In [58]:
# 3. Build rosters
rostersDF = build_rosters(cdlDF)
rostersDF

         player                    team team_abbr
0         aBeZy            Atlanta FaZe       ATL
1       Cellium            Atlanta FaZe       ATL
2        Drazah            Atlanta FaZe       ATL
3          Simp            Atlanta FaZe       ATL
4         Beans           Boston Breach       BOS
5     Pentagrxm           Boston Breach       BOS
6     Priestahh           Boston Breach       BOS
7        Snoopy           Boston Breach       BOS
8      Clayster   Carolina Royal Ravens       CAR
9          FeLo   Carolina Royal Ravens       CAR
10        Gwinn   Carolina Royal Ravens       CAR
11       TJHaLy   Carolina Royal Ravens       CAR
12       Attach        Las Vegas Legion        LV
13          Gio        Las Vegas Legion        LV
14         Nero        Las Vegas Legion        LV
15      oJohnny        Las Vegas Legion        LV
16   Diamondcon  Los Angeles Guerrillas       LAG
17      Estreal  Los Angeles Guerrillas       LAG
18         Fame  Los Angeles Guerrillas       LAG
19       Flames  Los Angeles Guerrillas       LAG
20       Ghosty     Los Angeles Thieves       LAT
21  JoeDeceives     Los Angeles Thieves       LAT
22        Kremp     Los Angeles Thieves       LAT
23       Nastie     Los Angeles Thieves       LAT
24        Lucky          Miami Heretics       MIA
25      MettalZ          Miami Heretics       MIA
26        ReeaL          Miami Heretics       MIA
27        Vikul          Miami Heretics       MIA
28     Accuracy         Minnesota ROKKR       MIN
29      Gunless         Minnesota ROKKR       MIN
30         Lynz         Minnesota ROKKR       MIN
31       Standy         Minnesota ROKKR       MIN
32        HyDra      New York Subliners      NYSL
33       KiSMET      New York Subliners      NYSL
34          Sib      New York Subliners      NYSL
35         Skyz      New York Subliners      NYSL
36        Dashy             OpTic Texas        TX
37        Kenny             OpTic Texas        TX
38         Pred             OpTic Texas        TX
39      Shotzzy             OpTic Texas        TX
40           04           Seattle Surge       SEA
41       Abuzah           Seattle Surge       SEA
42       Breszy           Seattle Surge       SEA
43         Huke           Seattle Surge       SEA
44       CleanX           Toronto Ultra       TOR
45        Envoy           Toronto Ultra       TOR
46      Insight           Toronto Ultra       TOR
47        Scrap           Toronto Ultra       TOR

In [60]:
# 3. Build initial player props 
initial_player_props = build_intial_props(rostersDF)
initial_player_props

      player           team team_abbr  prop  line
0      aBeZy   Atlanta FaZe       ATL     0  50.5
1    Cellium   Atlanta FaZe       ATL     0  50.5
2     Drazah   Atlanta FaZe       ATL     0  50.5
3       Simp   Atlanta FaZe       ATL     0  50.5
4      Beans  Boston Breach       BOS     0  50.5
..       ...            ...       ...   ...   ...
187    Scrap  Toronto Ultra       TOR     3  22.0
188    Dashy    OpTic Texas        TX     3  22.0
189    Kenny    OpTic Texas        TX     3  22.0
190     Pred    OpTic Texas        TX     3  22.0
191  Shotzzy    OpTic Texas        TX     3  22.0

[192 rows x 5 columns]

In [61]:
# 4. Combine initial player props with current player props
updated_player_props = merge_player_props(initial_player_props, player_props_df, rostersDF)
updated_player_props.head(96)

     player  prop           team team_abbr  line
0     aBeZy     0   Atlanta FaZe       ATL  50.5
1   Cellium     0   Atlanta FaZe       ATL  50.5
2    Drazah     0   Atlanta FaZe       ATL  50.5
3      Simp     0   Atlanta FaZe       ATL  50.5
4     Beans     0  Boston Breach       BOS  53.5
..      ...   ...            ...       ...   ...
91    Scrap     1  Toronto Ultra       TOR  22.0
92    Dashy     1    OpTic Texas        TX  22.0
93    Kenny     1    OpTic Texas        TX  22.0
94     Pred     1    OpTic Texas        TX  22.0
95  Shotzzy     1    OpTic Texas        TX  22.0

[96 rows x 5 columns]

In [63]:
updated_player_props.tail(48)

          player  prop                    team team_abbr  line
144        aBeZy     3            Atlanta FaZe       ATL  22.0
145      Cellium     3            Atlanta FaZe       ATL  22.0
146       Drazah     3            Atlanta FaZe       ATL  22.0
147         Simp     3            Atlanta FaZe       ATL  22.0
148        Beans     3           Boston Breach       BOS  23.5
149    Pentagrxm     3           Boston Breach       BOS  22.0
150    Priestahh     3           Boston Breach       BOS  22.0
151       Snoopy     3           Boston Breach       BOS  24.5
152     Clayster     3   Carolina Royal Ravens       CAR  20.5
153         FeLo     3   Carolina Royal Ravens       CAR  19.5
154        Gwinn     3   Carolina Royal Ravens       CAR  23.5
155       TJHaLy     3   Carolina Royal Ravens       CAR  22.0
156   Diamondcon     3  Los Angeles Guerrillas       LAG  22.0
157      Estreal     3  Los Angeles Guerrillas       LAG  23.5
158         Fame     3  Los Angeles Guerrillas       LAG  21.5
159       Flames     3  Los Angeles Guerrillas       LAG  21.5
160       Ghosty     3     Los Angeles Thieves       LAT  24.0
161  JoeDeceives     3     Los Angeles Thieves       LAT  23.5
162        Kremp     3     Los Angeles Thieves       LAT  23.0
163       Nastie     3     Los Angeles Thieves       LAT  22.0
164       Attach     3        Las Vegas Legion        LV  22.5
165          Gio     3        Las Vegas Legion        LV  22.5
166         Nero     3        Las Vegas Legion        LV  24.0
167      oJohnny     3        Las Vegas Legion        LV  22.5
168        Lucky     3          Miami Heretics       MIA  20.0
169      MettalZ     3          Miami Heretics       MIA  21.5
170        ReeaL     3          Miami Heretics       MIA  23.5
171        Vikul     3          Miami Heretics       MIA  22.5
172     Accuracy     3         Minnesota ROKKR       MIN  21.0
173      Gunless     3         Minnesota ROKKR       MIN  20.5
174         Lynz     3         Minnesota ROKKR       MIN  23.5
175       Standy     3         Minnesota ROKKR       MIN  22.5
176        HyDra     3      New York Subliners      NYSL  22.0
177       KiSMET     3      New York Subliners      NYSL  22.0
178          Sib     3      New York Subliners      NYSL  22.0
179         Skyz     3      New York Subliners      NYSL  22.0
180           04     3           Seattle Surge       SEA  24.0
181       Abuzah     3           Seattle Surge       SEA  20.5
182       Breszy     3           Seattle Surge       SEA  21.5
183         Huke     3           Seattle Surge       SEA  22.5
184       CleanX     3           Toronto Ultra       TOR  22.0
185        Envoy     3           Toronto Ultra       TOR  22.0
186      Insight     3           Toronto Ultra       TOR  22.0
187        Scrap     3           Toronto Ultra       TOR  22.0
188        Dashy     3             OpTic Texas        TX  22.0
189        Kenny     3             OpTic Texas        TX  22.0
190         Pred     3             OpTic Texas        TX  22.0
191      Shotzzy     3             OpTic Texas        TX  22.0